### ISSUE TITLE
Migrate to cmake

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models-cpp#2]

**Comment by shinsuke-koyama** [comment]
@kyakuno 
yolov3-faceをcmakeに移行しました。
ailiaライブラリの置き場所を環境変数 AILIA_LIBRARY_PATHに設定して頂く必要があります。
以下Linuxでの使い方の例です。(yolov3-faceにて)
  export AILIA_LIBRARY_PATH=[pass_to_ailia]/library
  mkdir build && cd build
  cmake ..
  make install
  cd ..
  ./yolov3.sh [options]
なお、Windows版ではVisualStudioでビルドしたbuild/Debug/yolov3-face.exeをyolov3-face直下にコピーしてからyolov3-face.batを実行して頂く必要があります。
